### ISSUE TITLE
[v2] sosync v2 test on demos instance

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/sosync#37]
## Basic Tests

Company
- [x] Create Company FSO > FS
- [x] Update Company FSO > FS
- [x] Create Company FS > FSO
- [x] Update Company FS > FSO

Todo:
- [ ] @Mike - Show sosync_write_date in res.company form view

Person
- [ ] Create Person FSO > FS
- [ ] Update Person FSO > FS
- [ ] Create Person FS > FSO
- [ ] Update Person FS > FSO

BPK
- [ ] Create BPK-Request FSO > FS
- [ ] Update BPK-Request FSO > FS
- [ ] Discuss: Do we need the other direction? Ask Marcus if File Import is still needed ...

TODO:
- [ ] @Mike json serialize fehler on force bpk und fehler verschleiert!

Check:
- Data
- Average Total Speed
- Partial Speeds

## Concurrent Write Test

1. Create and sync a Person record "Max[1]" "Concurrent" with counter in Firstname
2. Parallel update the created ```Person``` record in FS and FSO every 500 ms for more than two minutes.

Expected Results:
- Check if the last update wins and if the job will continue to restart itself until no more writes happen
- Check if "run counter exceeded" will be triggered
- Check CPU and ressources

## Service not available Test

- Stop FSO while Updates run
- Stop FS while Updates run (Firewall rule)
- Stop sosync v2 while Updates run

Checks:
- Service continues on correct Job (no Job is skipped)
- No data is lost or incorrect
- Service continues immediately if services is available again

## Mass Test
FSO:
- Import massive Data in FSO
- Import massive Data in FS

FS:
- Mass Update Data in FSO
- Mass Update in FS

Check:
- Performance

## Child Job Tests

TODO:

**Comment by michaelkarrer81** [comment]
# TODO:  Make sure there is the same time on the server !!!
- [x] @michaelkarrer81 enable ntp service on all linux server
- [ ] @michaelkarrer81 Implement time drift check and service stop in odoo
- [ ] @kaipm Implement sosync v2 check on startup and on job start for time drift
  - [x] Check fso server
  - [x] Check sosync server
  - [ ] Check mssql server
- [ ] @thecro Implement service warning and stop for Fundraising Studio if time-drift ist too large

# All flows
- [x] Never save passwords in logs, see issue #38

# Company Flow (res.company, dbo.xBPKAccount)
## FSO > FS create
- [x] @michaelkarrer81 sosync has still no access if company is not a child company
    INFO: Das entspricht leider dem standard Verhalten von odoo. Es ist angedacht das der User im GUI die Firma wechselt um Zugriff auf die andere Firma zu erhalten was seine Standard-Company ID ändert bis er wieder wechselt. Ich könnte das zwar über Security-Rules ändern es ist jedoch einfacher beim ```create``` neuer Firmen diese einfach als Child der Instance-Main-Company anzulegen. Das entspricht dann zwar dem was der sosyncer eh schon gemacht hat ist aber jetzt korrekt in der Business Logik von FS-Online.
- [x] @michaelkarrer81 ```Job Date``` wird nicht korrekt in den sosync jobs eingetragen!!!
- [x] @kaipm ```Target Record ID``` sollte befüllt sein
- [ ] @kaipm ```Target Data After``` sollte mit den Objektdaten befüllt sein
- [x] @kaipm ```sosync_write_date``` milisekunden präzision muss auch in FS erhalten bleiben
- [x] Name ist korrekt befüllt
- [x] fso_id ist in FS korrekt befüllt
## FSO > FS update
- [x] geht alles
- [x] ```Target Data Before``` ist vorhanden
- [ ] @kaipm ```Target Request(s)``` sollten die echten sql Befehle enthalten
- [ ] @michaelkarrer81 Durations must be None not 0
## FS > FSO create
- [ ] @thecro Nach create in FS per SQL wurde  kein Job von FS and den sosyncer übertragen
## FS > FSO update
- [ ] @thecro Nach update in FS per SQL wurde  kein Job von FS and den sosyncer übertragen

**Comment by michaelkarrer81** [comment]
# Partner Flow (res.partner, dbo.Person)
## @thecro FSO Felder fehlen im Partner Flow
- [ ] gender
    can be synced, but we have more possibilities than just male and female
    studio values:
    TypenID	TypenBezeichnung	        Wert	Erläuterung
    290	        Person_GeschlechttypID	M	        Männlich
    291	        Person_GeschlechttypID	W	        Weiblich
    292	        Person_GeschlechttypID	MM	        Mänlich/Männlich
    293	        Person_GeschlechttypID	WW	        Weiblich/Weiblich
    294	        Person_GeschlechttypID	WM	        Weiblich/Männlich
    295	        Person_GeschlechttypID	MW	        Männlich/Weiblich
    ATTENTION: Only male, female, and other makes sense in FS-Online. Because of this we will only map "female" "male" and "other": If other is selected in FSO it will not change any existing special settings in FS like "male/male".
- [ ] lang
    can be synced, should be taken from default value of dboTypen when not filled at dboPerson record (SprachetypID)
    need to be discussed in group since there is no official mapping to the lang strings (de_de, it_it,...)
    - [ ] @thecro INFO: Sollte ein neues Feld bei dboPerson in FS werden um Kollisionen mit dem bestehenden Feld zu vermeiden. Ein "mapping" vom neuen auf das alten Feld kann dann immer noch in FS vorgenommen werden falls gewünscht.
- [ ] phone
    extend partner flow to know different types (TelefontypID is the terminator for the type)
    - [x] ready for test
    - [x] @thecro phone numbers must be sorted by ID to make sure to overwrite the "last valid" telephone number
- [ ] mobile
    same as phone
    - [x] ready for test
- [ ] fax
    same as phone and mobile
    - [x] ready for test
- [ ] post_office_box_web
    is a property of personadresse, can be synced, is only for ch customers
    talk to harry
- [ ] country_id
    belongs to address
    how to deal with the values in sosync processing? any dictionary?
    create function to convert landid to iso and vice versa in mssql
    - [x] ready for test
- [ ] anrede_individuell
    is a property of dbo.PersonAdresse, can be synced
    - [x] ready for test
- [ ] company_name_web
    will be synced, when persontypid = "firma"
    wait for harry to discuss and rethink
- [ ] donation_deduction_disabled
    wait for harry - ask if he did something already
- [ ] donation_receipt_web
    sync with zgruppedetailid 20168, same as email nl group
    - [x] ready for test
- [ ] BPKForcedZip
    will be synced
    - [x] ready for test

## FSO > FS create
- [x] @kaipm ```Target Record ID``` sollte befüllt sein

## FSO > FS update
- [x] @kaipm ```Target Record ID``` sollte befüllt sein

## FS > FSO create
- [x] @kaipm ```Target Record ID``` sollte befüllt sein

## FS > FSO update
- [x] @kaipm ```Target Record ID``` sollte befüllt sein

## Vereinbarungen und Abläufe die offen sind
- [ ] @thecro Anlage einer neuen zeitlich unbegrenzten Adresse wenn zeitl. begr. vorhanden ist?
- [ ] Manuelles duplizieren der vorhandenen Adressen bei sosync v2 start ?
    can be done but should be rethought again
- [ ] Double Opt In bei Newsletter Zustimmung Wo?, Workflow?, neues FSO Feld ?
- [ ] Lieferadresse und Rechnungsadresse ?!?
    eventually create new address, but how to determine in syncer?
- [ ] soll legal_terms_web OptIn übertragen werden? Übertragen auf Sale Order?
    no, since it's a user interface field which will not allow the order to be submittet when set to false!
- [ ] ```donation_deduction_disabled``` muss in FS eingebaut werden
    wait for harry
## birthdate_web
- [x] @kaipm Format derzeit nicht ok geparsed
- [ ] @kaipm @mike Zeitzonen Test AUCH im odoo - sollte immer selber tag bleiben: Sicherstellen das KEINE TZ transformation passiert !!!!

## Sebis TODO:
- [ ] PersonAdresseBlock aufbauen nach insert
- [ ] PersonEmailGruppe NL geht noch nicht
- [ ] PersonGruppe Donation... geht noch nicht

**Comment by michaelkarrer81** [comment]
- [x] @Mike DONE: sosync_write_date darf nicht Pflicht sein
